### PR TITLE
(Fix #8) Add conditional reorder option

### LINKED ISSUE #8: Disabling automatic tabs switching
Can you add an option to disable automatic tabs switching when I click on them. I find it hard to focus when my tabs constantly switching the positions after I click on them.

### PR DESCRIPTION
**Pull request by Megaemce**
Add option to reorder tabs conditionally. This should fix the issues #8

### CODE REVIEW

**Comment by Dylan700** [comment]
Hey thanks so much for contributing, greatly appreciated! It seems you just need to fix the package.json file; there is a comma missing on line 37. If you could please test on your end before pushing too that would be great. I will also test myself once it's passing the CI check.

Let me know how you go!

**Comment by Megaemce** [comment]
Hey @Dylan700, nice to see you’re still around! I was actually worried you might have disappeared and left the project. Sorry about the missing colon typo—I’ve never created a VSC extension before, so I wasn’t sure how to test it properly. I found your project and liked it, but I wasn’t a fan of the shuffle tab behavior, so I added a new PR.

The fix is done according to your comment.

**Comment by Dylan700** [comment]
Thanks @Megaemce , greatly appreciated!

Haha haven't disappeared. Just busy with other projects. Apologies for the delay, glad you find it useful.

I'll run the checks shortly and we should be good to merge!

**Comment by Megaemce** [comment]
Unfortunately, my mind is currently preoccupied with other things, so I simply don't have the capacity to test it right now. However, the changes I made were minimal, so they should be fine. 😬

**Comment by Dylan700** [comment]
> Unfortunately, my mind is currently preoccupied with other things, so I simply don't have the capacity to test it right now. However, the changes I made were minimal, so they should be fine. 😬

Understoood and no worries, I'll just test on my end then when I get the chance! Thanks again for all your help

**Comment by Megaemce** [comment]
Any update on that?

**Comment by Dylan700** [comment]
> Any update on that?

Hey! Yes, I still currently need to test. I updated my OS and it's screwed with the set-up, so it's taken longer than expected. It should be fine, but I just want to run it before merging.

**Comment by Megaemce** [comment]
🤔🤌

**Comment by Dylan700** [comment]
Thanks for your contributions! I'll update the readme and add your name somewhere if you like

**Comment by Megaemce** [comment]
That's fine without it. Glad that you finally delivered!

**Comment by Megaemce** [comment]
I think you need to increase the release number for this change to apear in the vs marketplace

**Comment by Dylan700** [comment]
Thanks for your patience @Megaemce! I've just released the new version to the marketplace now :)

**Pull request merged**
